# Generated by Django 2.2.3 on 2019-07-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190731_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
